manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: refil
      revision: bt75
      import: app/west.yml
  self:
    path: config
